# Generated by Django 2.0.2 on 2018-04-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('university_name', models.CharField(blank=True, max_length=200)),
                ('class_10_percent', models.IntegerField(blank=True)),
                ('class_12_percent', models.IntegerField(blank=True)),
                ('bachelors_percent', models.IntegerField(blank=True)),
                ('work_exp', models.CharField(max_length=200)),
                ('german_grade', models.CharField(max_length=20, verbose_name='German Grade (For eg: A1,A2,etc)')),
                ('semester', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
