# Generated by Django 2.0.2 on 2018-04-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterdata',
            name='bachelors_percent',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='enterdata',
            name='class_10_percent',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='enterdata',
            name='class_12_percent',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
